author: tex
name: butterfly
main: com.butterfly.ButterflyCore
api-version: 1.20
version: ${project.version}

commands:
  gma:
    aliases: [gm2]
  gmc:
    aliases: [gm1]
  gm:
    aliases: []
  gms:
    aliases: [gm0]
  gmsp:
    aliases: [gm3]
  build:
    aliases: [b]
  vanish:
    aliases: [v]
  inv:
    aliases: [inventory]
  fly:
    aliases: [f]
  item:
    aliases: [i]
  nick:
    aliases: [nickname]
  unnick:
    aliases: [unnickname]
  disguise:
    aliases: []
  undisguise:
    aliases: []
  heal:
    aliases: [h]
  staffchat:
    aliases: [sc]
  push:
    aliases: [p]
  broadcast:
    aliases: [bc]
  clear:
    aliases: [ci]
  spawnmob:
    aliases: []
